version: '3.8'

services:
  app:
    ports:
      - "8000:80"
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DB_HOST=db
      - DB_PASSWORD=mypassword
    depends_on:
      db:
        condition: service_started
  
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
  
volumes:
  pg-data:
      name: pg-data
