version: '3.8'

services:
  app:
    ports:
      - "8000:80"
    build:
      context: ./backend
      dockerfile: Dockerfile
  
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
