# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches:
      - '**'
  pull_request:
    branches: [ master ]

jobs:
     
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --output-file=flake8_output.txt
    - name: Test with pytest
      run: |
        pip install pytest
        pytest -m console -q -vv --color="yes" --cov=. --html=report_${{ matrix.platform }}.html --self-contained-html --report-log=report_${{ matrix.platform }}.json
    - name: Coverage
      run: |
        coverage xml -o coverage-all.xml
    - name: Upload coverage results
      uses: actions/upload-artifact@v1
      with:
        name: coverage-results
        path: coverage-all.xml
    - name: Upload test report
      uses: actions/upload-artifact@v1
      with:
        name: test-report
        path: report_${{ matrix.platform }}.html
    - name: Upload test report JSON
      uses: actions/upload-artifact@v1
      with:
        name: test-report
        path: report_${{ matrix.platform }}.json
    - name: Upload Flake8 report
      uses: actions/upload-artifact@v1
      with:
        name: test-report
        path: flake8_output.txt
    - name: MyPy
      run: |
        mypy --html-report report --show-error-codes --ignore-missing-imports analyze_delicious.py
    - name: Upload Mypy report
      uses: actions/upload-artifact@v1
      with:
        name: test-report
        path: report

  
  sonar-qube:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@master
      - name: Download coverage results
        uses: actions/download-artifact@v1
        with:
          name: coverage-results
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
